### ISSUE TITLE
Skywalking-agent修改了那里

### ISSUE THREAD

**Issue by Cool-Coding** [cao2068959/chy-skywalking-plugins-threadpool#5]
> 因为 原生的apm-agent.jar，在bytebuddy修改ThreadPoolExecutor字节码前就已经把ThreadPoolExecutor加入到虚拟机(写入log的时候会启动线程池)，导致织入失败 所以需要使用我提供的apm-agent.jar来让ThreadPoolExecutor不要过早加载

您好，您说修改了SkywalkingAgent.java,但我比较了您修改后的java文件和原始7.0版本的java文件，发现premain方法最后多了一句： SnifferConfigInitializer.pulginInitCompleted();，其它地方一样，请问这样就能让ThreadPoolExecutor不要过早加载吗？ 望解惑

**Comment by cao2068959** [comment]
线程池提前加载的地方在于 log， 在设置bytebuddy之前就有很多地方使用了log去打日志， log里面的实现是使用到了ThreadPool， 就导致ThreadPool没有经过bytebuddy修改就加载到了jvm中， 所以我还修改了log实现里面的代码，在bytebuddy设置之前都会关闭threadPool的使用， 直到 SnifferConfigInitializer.pulginInitCompleted() 执行完成后，log才会继续使用ThreadPool去输出日志

**Comment by Cool-Coding** [comment]
知道了，感谢！发自我的华为手机-------- 原始邮件 --------发件人： BigNose Cat ***@***.***>日期： 2021年6月28日周一 18:55收件人： cao2068959/chy-skywalking-plugins-threadpool ***@***.***>抄送： Cool-Coding ***@***.***>, Author ***@***.***>主    题： Re: [cao2068959/chy-skywalking-plugins-threadpool] Skywalking-agent修改了那里 (#5)
线程池提前加载的地方在于 log， 在设置bytebuddy之前就有很多地方使用了log去打日志， log里面的实现是使用到了ThreadPool， 就导致ThreadPool没有经过bytebuddy修改就加载到了jvm中， 所以我还修改了log实现里面的代码，在bytebuddy设置之前都会关闭threadPool的使用， 直到 SnifferConfigInitializer.pulginInitCompleted() 执行完成后，log才会继续使用ThreadPool去输出日志
