### ISSUE TITLE
attempted to change superclass or interfaces

### ISSUE THREAD

**Issue by zjutkz** [cao2068959/chy-skywalking-plugins-threadpool#7]
老哥你好，我自己基于8.6.0实现的线程池插件，具体原理和你差不多就是切了ThreadPoolExecutor的构造函数，但是发现ByteBuddy没办法增强ThreadPoolExecutor，报错是java.lang.UnsupportedOperationException: class redefinition failed: attempted to change superclass or interfaces，这个你有遇到过吗？

**Comment by zjutkz** [comment]
解决了，原来必须要处理一下日志打印，不然ThreadPoolExecutor就在增强之前被加载了

**Comment by tjzheng1002** [comment]
@zjutkz 我也遇到了同样的报错，请问你是怎么解决的，我也是基于8.6.0实现的。

**Comment by zjutkz** [comment]
> @zjutkz 我也遇到了同样的报错，请问你是怎么解决的，我也是基于8.6.0实现的。

就按这个工程里的做法。
报这个错的原因是因为在增强线程池之前Skywalking已经在打日志的时候创建线程池了，做法就是设置个标记位来解决，你对比看下工程里的SkyWalkingAgent这个类和开源版本的区别就知道了。
